// Global using directives

global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;
global using AdaptiveCards;
global using Microsoft.Agents.Builder;
global using Microsoft.Agents.Builder.App;
global using Microsoft.Agents.Builder.State;
global using Microsoft.Agents.Core.Models;
global using Microsoft.Agents.Hosting.AspNetCore;
global using Microsoft.ApplicationInsights.Channel;
global using Microsoft.ApplicationInsights.DataContracts;
global using Microsoft.ApplicationInsights.Extensibility;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.ApplicationModels;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Graph.Beta;
global using Microsoft.Graph.Beta.Models;
global using Swashbuckle.AspNetCore.Annotations;
global using Teams.Notifications.Api.Extensions;
global using Teams.Notifications.Api.Models;
global using Teams.Notifications.Api.Services.Interfaces;
global using AdaptiveCard = AdaptiveCards.AdaptiveCard;