{{- $name := include "devops-teams-notification-api.name" . -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
    version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        app.kubernetes.io/name: {{ $name }}
        version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: "compute-aks-devops-{{ .Values.environment }}-k8s-sa"
      containers:
        - name: {{ $name }}
          image: computeaksacr.azurecr.io/{{ $name }}:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            periodSeconds: 20
            timeoutSeconds: 30
            httpGet:
              path: {{ .Values.healthUrl }}
              scheme: HTTP
              port: 8080         
          readinessProbe:
            periodSeconds: 20
            timeoutSeconds: 30
            httpGet:
              path: {{ .Values.healthUrl }}
              scheme: HTTP
              port: 8080
          env:
          - name: ASPNETCORE_URLS
            value: "http://+:8080"
        {{- range $key, $value := .Values.env }}
          - name: {{ $key | upper | replace "." "_" }}
            value: {{ $value | quote }}
        {{- end }} 
      nodeSelector:
        agentpool: platform