# This folder contains no application-specific settings and can be reused as is.
replicaCount: 1
nameOverride: ""
port: 8080
environment: dev
serviceAccountName: helm-dotnet-sa-change-me
clientId: change-me
env:
  ASPNETCORE_ENVIRONMENT: "dev"
