name: CI for Teams Notifications API

on:
  workflow_dispatch:

  pull_request:
    paths:
      - .github/workflows/api-ci.yaml
      - .github/workflows/shared-app-ci-workflow.yaml
      - src/Teams.Notifications.Api/**

permissions:
  id-token: write
  contents: read

jobs:
  TeamsNotificationApi_CI:
    uses: ./.github/workflows/shared-app-ci-workflow.yaml
    with:
      applicationName: Teams.Notifications.Api
