name: Shared Application CI Workflow

on:
  workflow_call:
    inputs:
      applicationName:
        type: string
        required: true
        description: "Application Name"

jobs:
  app_ci:
    name: Build and unit test ${{ inputs.applicationName }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: expose app name into env
        run: |
          echo "APPLICATION_NAME=${{ inputs.applicationName }}" >> $GITHUB_ENV

      - name: run unit tests
        working-directory: ./src/${{ env.APPLICATION_NAME }}.Tests
        run: |
          dotnet test -v:q --nologo --filter TestCategory=Unit /p:CollectCoverage=true --logger GitHubActions
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.5
        with:
          reports: "./tests/*/coverage.cobertura.xml" # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
          targetdir: "coverage-results" # REQUIRED # The directory where the generated report should be saved.
          reporttypes: "HtmlInline;MarkdownSummaryGithub"
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: coverage-results
      - name: Publish coverage in build summary # Only applicable if 'MarkdownSummaryGithub' or one of the other Markdown report types is generated
        run: cat coverage-results/SummaryGithub.md >> $GITHUB_STEP_SUMMARY # Adjust path and filename if necessary
        shell: bash
      - name: docker build test
        working-directory: ./src/
        run: |
          docker build . -f ./$APPLICATION_NAME/Dockerfile
