name: Shared Application CI Workflow

on:
  workflow_call:
    inputs:
      applicationName:
        type: string
        required: true
        description: "Application Name"

jobs:
  app_ci:
    name: Build and unit test ${{ inputs.applicationName }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: expose app name into env
        run: |
          echo "APPLICATION_NAME=${{ inputs.applicationName }}" >> $GITHUB_ENV

      - name: run unit tests
        working-directory: ./src/${{ env.APPLICATION_NAME }}.Tests
        run: |
          dotnet test -v:q --nologo --filter TestCategory=Unit /p:CollectCoverage=true --logger GitHubActions
      - name: run integration tests
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: generate coverage report
        working-directory: ./
        run: reportgenerator -reports:"./tests/*/coverage.cobertura.xml" -targetdir:"test-results" -reporttypes:Html
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
      - name: docker build test
        working-directory: ./src/
        run: |
          docker build . -f ./$APPLICATION_NAME/Dockerfile
